### ISSUE TITLE
Compatibility with version 3.38.x for this plugin

### ISSUE THREAD

**Issue by fghamsary** [sonatype-nexus-community/nexus-repository-composer#103]
This plugin is not compatible with 3.38.+ of the changes on the search facet.

The class ComposerRecipeSupport uses `org.sonatype.nexus.repository.search.SearchFacet` which doesn't exist anymore on the new version of Nexus.
The solution is simple and I'll create a PR for it.
The new class which should be used is: `org.sonatype.nexus.repository.search.ElasticSearchFacet`

**Comment by jba31** [comment]
Same issue

If you have the following issue while downgrading Nexus to 3.37.3
 [FelixStartLevel] *SYSTEM org.sonatype.nexus.upgrade.internal.orient.UpgradeServiceImpl - The database model for maven is 1.3, but the latest supported by this version of nexus is 1.2

Fix
```
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/java -jar  /opt/sonatype/nexus/lib/support/nexus-orient-console.jar
connect plocal:/nexus-data/db/config admin admin
select from upgrade_model_versions
update upgrade_model_versions set maven='1.2'
```
[source](https://serveradminhub.wordpress.com/2020/12/03/nexus-is-not-coming-up-incompatible-sonatype-work-database-model-detected/)

**Comment by PhilippHeuer** [comment]
Thanks for the fix :)

Stopping/downgrading is a little more troublesome on k8s with a pvc when the pod instantly quits because of the error. So i build the .kar with your patch for myself as hotfix (which worked great). Just wanted to share this here for anyone else who finds the issue:

[nexus-repository-composer-0.0.19-bundle.kar.zip](https://github.com/sonatype-nexus-community/nexus-repository-composer/files/8314626/nexus-repository-composer-0.0.19-bundle.kar.zip)

**Comment by EugenMayer** [comment]
Just in case anybody needs it - i did not want to change our init container and needed a non-zipped variant. https://github.com/EugenMayer/nexus-repository-composer/releases/tag/composer-parent-0.0.19-pre1

just re-published what @PhilippHeuer did (it's his build) - @PhilippHeuer i hope you do not mind, let me know!

**Comment by Yermanaco** [comment]
Thanks for the patch uploaded here it works 😄  but do you know when this issue will be fixed and published in [central repository ](https://search.maven.org/artifact/org.sonatype.nexus.plugins/nexus-repository-composer)?

**Comment by max464** [comment]
We are also looking forward to this patch.
Guys please repeat test.
