### ISSUE TITLE
packages.json file could not be downloaded 

### ISSUE THREAD

**Issue by pengjun-gz** [sonatype-nexus-community/nexus-repository-composer#106]
![image](https://user-images.githubusercontent.com/21036915/160737101-e70629d6-9cd6-41c6-8e95-95c1ea747061.png)

**Comment by pengjun-gz** [comment]
i know the reason

**Comment by Vormillion** [comment]
What's the reason?

**Comment by zwp201301** [comment]
> ![image](https://user-images.githubusercontent.com/21036915/160737101-e70629d6-9cd6-41c6-8e95-95c1ea747061.png)

问题是出在哪里呢？地址不对还是Nexus那缺少配置？

**Comment by sagarkhushalani** [comment]
@pengjun-gz  what was the reason, please?
