### ISSUE TITLE
Security Vulnerability: API Mass Assignment

### ISSUE THREAD

**Issue by yj0930** [sonatype-nexus-community/nexus-repository-composer#107]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
* Using AppScan, Nexus has a HIGH level security vulnerability: API Mass Assignment

* **What feature or behavior is this required for?**
* Security

* **How could we solve this issue? (Not knowing is okay!)**
* /service/extdirect should be protected under authorization

* **Anything else?**
* AppScan report related screenshot was attached
![Nexus Security Report pdf and 7 more pages - Work - Microsoft​ Edge 4_13_2022 5_37_36 PM](https://user-images.githubusercontent.com/8189913/163147663-9ce8e3f5-e3ce-4374-8f77-e8b8c6d4090e.png)

**Comment by mpiggott** [comment]
See for reporting vulnerabilities - https://github.com/sonatype-nexus-community/nexus-repository-composer/blob/master/SECURITY.md

It should be for a specific problem - generally scans are filled with generic noise.
