### ISSUE TITLE
Ready for Nexus 3.16.2-01 ?

### ISSUE THREAD

**Issue by jcolfej** [sonatype-nexus-community/nexus-repository-composer#42]
* **What are you trying to do?**
Prepare upgrade of Nexus to 3.16.2-01.

* **What feature or behavior is this required for?**
Is this plugin ready for Nexus 3.16.2-01 ?

* **How could we solve this issue?**
Not knowing

* **Anything else?**
Coffee ?

**Comment by electrical** [comment]
I was running it fine on 3.16.2 without any issues.

**Comment by jcolfej** [comment]
Ok thx ;)
