### ISSUE TITLE
Plugin works with Nexus 3.19.1-01 ?

### ISSUE THREAD

**Issue by theopentag** [sonatype-nexus-community/nexus-repository-composer#53]
Hi.
Any chance that plugin works with Sonatype Nexus  3.19.1-01?

**Comment by theopentag** [comment]
any news ?

**Comment by tvanrielwendrich** [comment]
I dont want to explicitly say "Works on my machine". but, Works on my machine :-) 

![image](https://user-images.githubusercontent.com/50411291/67841329-1c96f780-faf8-11e9-9e9e-eadb0914eca1.png)

**Comment by theopentag** [comment]
@tvanrielwendrich sure, repository exist. But, i cannot upload any zip file to it. Always get 404 error

**Comment by tvanrielwendrich** [comment]
I uploaded a zip just fine. Are you sure you didn't accidentally made a typo in your username/password and in the repo path?

**Comment by theopentag** [comment]
Sure) i got an error:
`composer nexus-push --name=xxxxxxxxxxxx --url=https://nexus.xxxxxxxxxxxx.com/repository/xxxxxxxxxxxx-composer --username=******* --password=******* 0.0.1
[ZIP Archive] Archive into the subdirectory xxxxxxxxxxxx-0-0-1
Zip archive /tmp/nexus-pushadLUgx.zip done
Execute the Nexus Push for the URL https://nexus.xxxxxxxxxxxx.com/repository/xxxxxxxxxxxx-composer/packages/upload/xxxxxxxxxxxx/0.0.1...

                                                                                                                                                                     
  [GuzzleHttp\Exception\ClientException]                                                                                                                             
  Client error: `PUT https://nexus.xxxxxxxxxxxx.com/repository/xxxxxxxxxxxx-composer/packages/upload/xxxxxxxxxxxx/0.0.1` resulted in a `404 Not Found` response  
                                                                                                                                                                     

nexus-push [--name NAME] [--url URL] [--username USERNAME] [--password PASSWORD] [-i|--ignore [IGNORE]] [--ignore-dirs [IGNORE-DIRS]] [--ignore-by-git-attributes] [--] <version>
`

**Comment by tvanrielwendrich** [comment]
Make sure the name contains a vendor prefix
If your package is called `foo`, make sure the `--name` option is `theopentag/foo`. otherwise, nexus will attempt to interpret the version number as the package and there will be no version.

**Comment by theopentag** [comment]
@tvanrielwendrich you are right, problem was in --name. Thanks a lot.

**Comment by tvanrielwendrich** [comment]
Great!
