### ISSUE TITLE
repositories which configured as "disable redeploy" don't update the json file in "p"

### ISSUE THREAD

**Issue by alex-lx** [sonatype-nexus-community/nexus-repository-composer#59]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
We created a composer repository to store our release packages, so we disable redeploy on it to prevent overwrite the previous release.

* **What feature or behavior is this required for?**
New release page could be uploaded and the json in "p" directory should be updated. However, only the first version in the json file.
* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by tetram** [comment]
Hi,
It's a duplicate of #31 .
I fixed it in a PR but there is apparently no one to validate it.

**Comment by alex-lx** [comment]
@tetram 👍 Hope to merge it.

**Comment by alex-lx** [comment]
Close of the duplicate of #31
