### ISSUE TITLE
Implement Composer hosted repositories

### ISSUE THREAD

**Issue by fjmilens3** [sonatype-nexus-community/nexus-repository-composer#7]
There is currently no implementation for Composer hosted. We should determine the best way to implement this in a way that makes sense for the Nexus Repository Manager and user expectations.

For Composer a typical expectation is that the index is exactly that, and there are links to Git repositories that store the actual content (for example, the way Packagist works). This is a reasonable assumption for _proxy_ but is insufficient for _hosted_ since the actual artifacts are not being hosted by the repository manager in such a scenario (see the Bower implementation for confusion regarding this very issue).

A strawman proposal:

* Have a way to upload a .phar, .tar., or .zip file to an endpoint in a hosted repository. Store that as the actual "artifact". (Note that we should investigate how useful storing .phar archives will be in this case relative to the additional complexity.)
* Extract the metadata to figure out where the file goes in terms of the overall list of packages/structure.

If anyone from the greater community has feedback or suggestions, we're listening.

**Comment by philippreston** [comment]
+1

**Comment by fjmilens3** [comment]
Thanks for the reply back, @philippreston. I'm hoping I'll be able to get around to working on this story in the near term as well so the more we can learn from possible users the happier I'll be.

@prumand, since you've also been involved in discussions with us on Gitter, would this approach work for your team's use cases (if any) as well?

(The other approach I've debated with myself is to have a more Satis-like experience where you could enter a set of your own internal version control systems and then sync up the artifacts using a scheduled task that polls the registered repositories. I do think that would provide a better overall experience but runs counter to most of the out-of-the-box behavior we have in Nexus so it's a lot harder/riskier of an approach. I would like to avoid that approach if possible, but I want to make sure that those of you out there potentially using this thing will be able to live with that decision for the time being.)

**Comment by prumand** [comment]
Hi @fjmilens3,

during our hackweek, we expiremented with the hosted repo-typ as well. Basically we endet up with something like the strawman proposal. That made it easy to push our private packages to nexus, which where otherwise pulled via github.

From my point the other approach seems really complex. Wouldn't it make more sense for an own git repo type?

**Comment by fjmilens3** [comment]
> From my point the other approach seems really complex. From my point the other approach seems really complex. Wouldn't it make more sense for an own git repo type?

It would be, and even a Git repo by itself wouldn't be sufficient since you'd still need some kind of Packagist-style layer in front of your Git repos to monitor/poll them and generate the Composer information you need.

**Comment by fjmilens3** [comment]
@prumand, @philippreston, and @TheBay0r:

I've gotten around to doing a minimum-viable-product sort of hosted implementation. While I want to do more review and testing of it myself (and also pass it around within the team here), I was wondering if any of you could take a look at the proposed mechanism in the documentation and see if you feel that would meet your needs (see PR #12).

Essentially, there's going to be a `/packages/upload/{vendor}/{project}/{version}` endpoint that accepts a PUT containing a zip file with the same basic layout you'd expect for any Composer project (i.e. including a `composer.json`). Whatever file you upload there will end up being the dist for that particular vendor/project/version. For example, if you had a Git repo with your project, you could just create a tag for a release, then get the source zip for that and upload it to the correct repo; you could probably automate it with a script, and you wouldn't have to make changes to the `composer.json` at all.

I went with this approach as opposed to a single endpoint that accepts all files because the `version` is not a required field in the `composer.json` (see their [docs](https://getcomposer.org/doc/04-schema.md#version)). In fact, per the Composer docs, they'd recommend that you not go around editing that field at all if you can help it. I didn't want to add additional restrictions you'd have to follow just to support Nexus.

If you have any feedback or concerns, just reply on here as I'll be checking back with this.

**Comment by TheBay0r** [comment]
Thanks for mentioning me and sorry that it took me awhile to respond.

I just rolled the new docker container out for testing in our infrastructure. So far I was just able to do a quick check but I have to say you guys are awesome ! It worked well so far, and we now want to automate the release of our private packages. A big thank you from my side 😃
