### ISSUE TITLE
No .kar file in Central Repository

### ISSUE THREAD

**Issue by JakoD** [sonatype-nexus-community/nexus-repository-composer#70]
* **What are you trying to do?**
Download the .kar file from [The Central Repository](https://search.maven.org/artifact/org.sonatype.nexus.plugins/nexus-repository-composer) as suggested by [Easiest Install - Option 2](https://github.com/sonatype-nexus-community/nexus-repository-composer#option-2-download-a-kar-file-from-the-central-repository).

* **What feature or behavior is this required for?**
Setting up a containerized Nexus instance with the nexus-repository-composer plugin without having to compile it from source.

* **How could we solve this issue? (Not knowing is okay!)**
Have a .kar file in the repository alongside the .jar, sources.jar, etc. 
  or
Have more detailed instructions how to get a .kar file from there if it is already possible

**Comment by adrianovieira** [comment]
I suppose this a typo mistake.

I acctually may is a `.jar` file.

**Comment by joedragons** [comment]
@JakoD  Do you still not see it?  I see 2 files in your link provided.

**Comment by JakoD** [comment]
Yes, I still see no .kar file there. Also I'm quite sure it should be .kar, since https://help.sonatype.com/repomanager3/bundle-development/installing-bundles speaks of Apache Karaf files (.kar), too.

**Comment by TheGuit** [comment]
Other projet have this `kar` file, ex: https://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-repository-cpan/0.0.1/

And with this no need to build it with multiple stage Docker.

My knowledge of Maven & Java world are a bit short to update this. But yes it would be great if `kar` file was available on maven.org IMO.

**Comment by joedragons** [comment]
Ah I see what you mean now.  I was looking at something else.  Thanks for the clarifies.

**Comment by hboutemy** [comment]
looks like it was supposed to be done for release 0.0.4 in 48a76801845554fae87cbbc2b1dfd28a74dc234b but the result is not as expected https://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-repository-composer/0.0.4/

**Comment by ym2048** [comment]
@JakoD 
I generate the kar file through commands list as follow:

**Comment by ym2048** [comment]
@JakoD
I generate the kar file through commands list as follow:
git clone https://github.com/sonatype-nexus-community/nexus-repository-composer.git
cd nexus-repository-composer && git checkout composer-parent-0.0.4

create -p /docker/nexus3_data
chmod a+rw -R /docker/nexus3_data

docker run -d -p 8081:8081 --name nexus-repository-composer -v /docker/nexus3_data:/nexus-data nexus-repository-composer

then login the nexus container.
The generated kar file is in container directory
/opt/sonatype/nexus/deploy/

move the file to the volume directory /nexus-data
and you can get the kar file in /docker/nexus3_data

**Comment by jbguerraz** [comment]
Isn't it there already ? 

![image](https://user-images.githubusercontent.com/861556/85135341-39766b80-b23e-11ea-945c-1843bb54036a.png)

**Comment by JakoD** [comment]
It wasn't (and still isn't) there for 0.0.4
It seems it was fixed with [7e09e59](https://github.com/sonatype-nexus-community/nexus-repository-composer/commit/7e09e59d9262cec16630bc1f4ccdd73a519aeca2) (May 5th), thanks for fixing and thanks for pointing out that it is fixed now.

Since it's fixed I'm closing this issue.
