### ISSUE TITLE
Build fails when I use mvn clean package

### ISSUE THREAD

**Issue by sakhayadeep** [sonatype-nexus-community/nexus-repository-composer#76]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
```mvn clean package```

* **What feature or behavior is this required for?**
To get the .jar file. 

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by bhamail** [comment]
You can download a prebuilt `.jar` or `bundle.kar` file from Maven Central. See the `Maven Central` badge at the top of the README.md 

https://search.maven.org/search?q=g:%22org.sonatype.nexus.plugins%22%20AND%20a:%22nexus-repository-composer%22
