### ISSUE TITLE
Composer 2 / Packagist API v2 compatibility

### ISSUE THREAD

**Issue by func0der** [sonatype-nexus-community/nexus-repository-composer#93]
https://blog.packagist.com/deprecating-composer-1-support/
https://packagist.org/apidoc

Packagist proxy might stop working properly in the next weeks, because packages are cancelled out in the v1 api of Packagist.

There should be a migration to the new api.

Secondly since the new api is for the new composer version, we might need a parallel endpoint for those calls. This would result in no breaking changes for on-going users and a clear path for the new proxy.

Though I think, those might be different projects/issues. Any input on this from the project maintainers?

**Comment by eplightning** [comment]
I have some basic support for V2 in my fork (https://github.com/eplightning/nexus-repository-composer/commit/4d64b155a798ff512de3b571c8c1d48358796125) in case someone needs it

Both V1 and V2 are supported but there's no conversion between them - so if there's a package in `packagist` only visible for V2 users then only V2 clients will see them in Nexus as well.

**Comment by glukkkk** [comment]
> I have some basic support for V2 in my fork ([eplightning@4d64b15](https://github.com/eplightning/nexus-repository-composer/commit/4d64b155a798ff512de3b571c8c1d48358796125)) in case someone needs it
> 
> Both V1 and V2 are supported but there's no conversion between them - so if there are `packagist` packages only visible for V2 users then only V2 clients will see them in Nexus as well.

It works well! You should better make a PR with your commit here. Hope they will accept it!
